version: '3'

tasks:
  build:
    desc: Build quiz app.
    cmds:
      - go build -o bin/quiz main.go 
  run:
    desc: Run quiz app.
    cmds:
      - go run main.go
  clean:
    desc: Run go mod clean.
    cmds:
      - go clean -modcache && go mod tidy
  lint:
    desc: Run golangci-lint.
    cmds:
      - go mod tidy && golangci-lint run

